### PR TITLE
feat: Add command for shell completions generation

### PR DESCRIPTION
**Pull request by DSpeckhals**
This commit adds the ability to generate shell completions for Toml
Bombadil for several popular shells using `clap`'s builtin ability to
generate these scripts by introspecting the `App` and its `Args`.

An example for ZSH would be to run:
`bombadil generate-completions zsh > $an_fpath/_bombadil`.

This could also be utilized when packaging the app for various
distros.

### CODE REVIEW

**Comment by oknozor** [comment]
Nice one @DSpeckhals !

**Comment by oknozor** [comment]
Hey @DSpeckhals I have some trouble installing the completion files for zsh. 

```zsh
autoload -Uz compinit promptinit
compinit

fpath=(~/dotfiles/zsh/completions $fpath)
```
```
dotfiles/zsh
├── completions
│   └── bombadil_zsh
├── starship.toml
├── zshenv
└── zshrc`
```

Is this correct ?

**Comment by DSpeckhals** [comment]
@oknozor That looks right.

One way to test it out is to run `compdef ~/dotfiles/zsh/completions/bombadil_zsh bombadil` then reload zsh(`exec zsh`) and try again. If that works, then it must be a problem with the autoloading of the directory you're adding to the `$fpath`. This skips the autoloading, and lets you manually define. Also, make sure `bombadil` is on your `$PATH`...I think that makes a difference.

I also believe the convention is to name zsh completion files with just a trailing underscore `_bombadil`. I don't _think_ that makes a difference, though.

**Comment by DSpeckhals** [comment]
@oknozor I think I see the issue...in your script, you want prepend to the `$fpath` _before_ executing `autoload -Uz compinit promptinit`. Try switching those around and see of that works.

**Comment by oknozor** [comment]
@DSpeckhals It worked, thank you !

**Pull request merged**
