### PR TITLE
Ignore more vcs and temp file dirs and reload bombadil config on changes

### PR DESCRIPTION
**Pull request by svenstaro**
Before it would pick up stuff even in the internal `.git` dirs and such. This should get rid of that.

This also adds reloading of the bombadil config itself if changes are detected.

### CODE REVIEW

**Comment by svenstaro** [comment]
I think the failures are flaky tests and not my PRs fault.

**Comment by svenstaro** [comment]
@oknozor ping

**Comment by oknozor** [comment]
Hey @svenstaro I will not be able to look at this before  next week. I'll take a look as soon as I can

**Comment by svenstaro** [comment]
@oknozor How do you feel about this? I can rebase but only if there's upstream interest.

**Comment by oknozor** [comment]
Hey @svenstaro It's been a while.

This will not be needed when #156 is merged. Once it's merged `bombadil link` `bombadil watch` will relink only modified dotfiles, leaving the unmodified untouched. 

Also it now open the dotfiles and modify them instead of recreating them on each link command. This should solve some issue with app that have config hot reload (for instance alacritty)

**Pull request closed without merging**
