### PR TITLE
Use tera as templating engine

### LINKED ISSUE #77: [FEATURE] More powerful templating engine
**Is your feature request related to a problem? Please describe.**
Currently it's a bit cumbersome to use templating with files where a single variable will be substituted with multiple lines.
It just makes reading and managing dotfiles a bit annoying.

For example, this is one of my configuration files that's currently managed by toml-bombadil right now.

```
...

[[block]]
block = "hueshift"
step = 50
hue_shifter = "redshift"

__[i3status_config]__

[[block]]
block = "music"
player = "spotify"
max_width = 15
marquee = true
marquee_interval = 10
marquee_speed = 0.25
buttons = ["prev", "play", "next"]

...
```

The `i3status_config` variable is then specified for two different profiles:

Desktop:
```
i3status_config = ""
```

Laptop:
```
i3_layout = """
[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat0: {percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat1: {percentage}% {time}"
"""
```

**Describe the solution you'd like**
There are multiple full-featured templating engines out there.
I've personally worked with a few and I was quite pleased about the way they work and the amount of features they provide.

For example, this would allow us to declare the example above like this:

```
[[block]]
block = "hueshift"
step = 50
hue_shifter = "redshift"

__[#if profile == "laptop"]__
[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat0: {percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat1: {percentage}% {time}"
"""
__[#if]__

[[block]]
block = "music"
player = "spotify"
max_width = 15
marquee = true
marquee_interval = 10
marquee_speed = 0.25
buttons = ["prev", "play", "next"]
```

This makes the dotfiles much more readable, as one no longer has to switch between files to adjust the same configuration/code block.

I assume we have to guarantee backwards compatibility, which means that the delimiter syntax `__[]__` would have to stay the same.
- [Handlebars](https://github.com/sunng87/handlebars-rust) doesn't seem to support this. At least I couldn't find anything about it.
- [Tera](https://tera.netlify.app/docs/) is thinking about this: https://github.com/Keats/tera/issues/343
- [tinytemplate](https://github.com/bheisler/TinyTemplate) Doesn't seem to allow configure this either.
- [liquid](https://docs.rs/liquid/0.23.1/liquid/struct.ParserBuilder.html) seems to support this, but their API seems to be rather low-level.
- [askama](https://docs.rs/askama/0.11.0/askama/) actually does support [custom syntax](https://djc.github.io/askama/configuration.html).

This is obviously a problem.

Solutions could be:
- Find a library that allows to set custom delimiters
- We could try to hide the new functionality behind a feature flag.
    But I assume that this will result in very segmented code :/.
- A fork that'll be developed in parallel.

**Additional context**
Adding a full-featured templating engine would obviously add a bit of compile time, but at the same time it provides us with a lot features and it would probably remove a big chunk of custom parsing code from the project.

### PR DESCRIPTION
**Pull request by Nukesor**
Fixes #77

### CODE REVIEW

**Review by svenstaro — APPROVED** [review]
Looks good, simple and clean to me as is!

**Comment by svenstaro** [comment]
@Nukesor You could rebase this in order to make the CI happy.

**Comment by oknozor** [comment]
I am quite confident with the test harness but I really need to test this manually before going further (just came back from vacation so now I have time :)). 
Also @Nukesor can you make the commit a breaking change (`feat!: ...`) so the automatic bump will reflect that. 
Last but not least the documentation website needs to be updated accordingly.

**Comment by oknozor** [comment]
Actually the documentation is updated already, and after a quick test on my setup this works like a charm let's to this then. 
Great work @Nukesor !

**Pull request merged**
