### PR TITLE
Preinstall hooks

### PR DESCRIPTION
**Pull request by TravisDavis-ops**
Needed it so i added it. isn't that how open source works.

### CODE REVIEW

**Comment by oknozor** [comment]
Hey @TravisDavis-ops  thank you ! I am in vacation with only my phone. I will take a closer look and merge this in a couple of week.

**Comment by oknozor** [comment]
Hello @TravisDavis-ops, this works great but documentation and example must be updated accordingly, could you had this to you PR or shall I do it in a separate one ? 

If you want to do the doc part as well, the readme, config example and [website](https://oknozor.github.io/toml-bombadil/) must be updated to reflect these changes. 

Also you can add your git signature and github username to the author list in [cog.toml](https://github.com/oknozor/toml-bombadil/blob/main/cog.toml), this is used for changelog generation.

**Comment by TravisDavis-ops** [comment]
Np, I'll just add it to this one.

**Comment by TravisDavis-ops** [comment]
Ok I think i got ever thing

**Comment by oknozor** [comment]
Thank you @TravisDavis-ops  I will make a release soon !

**Pull request merged**
